Updated README.md
Mayank447/Pseudo-Spectral-Discretization pull request #17
Opened 2024-08-07 09:13 UTC by Mayank447

Updated README.md in sync with derivative 1D class

2024-08-08 08:31 UTC, chillenzer requested changes
Thanks for the effort.

Please keep in mind two things:
- Whenever you add explanation, comments, etc., to your project it should add more value than noise. A sentence vaguely saying "Something provides methods to work with <what's already in the name of Something>." is simply noise. In the best case, the user skips this sentence because it is obvious. In the worst case, it gets out of sync with the actual code and misleads the reader.
- Please have a look at the amount of mistakes and out-of-sync-ness that's already in this first version of the `README` and re-consider if you really want to maintain this level of detail twice (because we also want to have docstrings saying exactly the same).

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +The DiracOperator class provides several methods to work with the Dirac operator in both real and spectral domains.
That is not a helpful text. This information is obvious from the name. Better provide some useful information. What does "work with" mean? Maybe something like this
```suggestion
The `DiracOperator` class provides wrapping infrastructure to apply an operator defined by its `Spectrum` to a function defined by its vector of `coefficients` in `"real"` or `"spectral"` basis.
```

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +Applies the given Dirac operator to the input coefficients as per the given input and output spaces.
```suggestion
Applies the given Dirac operator to a function represented by its coefficient vector in the specified `"real"` or `"spectral"` basis.
```

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +- coefficients (np.ndarray): An array of coefficients in the input space.
```suggestion
- coefficients (np.ndarray): An array of coefficients in the input basis.
```

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +- np.ndarray: An array of coefficients in the output space.
```suggestion
- np.ndarray: An array of coefficients in the output basis.
```
Everywhere

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +The Derivative1D class provides methods to work with the 1D derivative operator in both real and spectral domains with periodic boundary conditions.
As above.

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +- eigenvalue_index (int): The index of the eigenvalue. This range is from 0 to L - 1.
```suggestion
- eigenvalue_index (int): The index of the eigenvalue. This range is from 0 to `num_lattice_points - 1`.
```
Everywhere

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +Private function to compute the eigenvalues of the 1D derivative operator.
Private functions are private and no public interface. Don't advertise them in a public section.

2024-08-08 08:31 UTC, chillenzer commented on README.md
> +Generates a discretized set of points representing the lattice structure in either the time or frequency domain.
```suggestion
Generates a discretized set of points representing the lattice structure in either the `"real"` or `"spectral"` domain. This defines the basis with respect to which the coefficients are to be interpreted, e.g., the `i`th eigenfunction in real-space basis representation is given by `spectrum.eigenfunction(i)(spectrum.lattice("real")).`
```

2024-08-09 06:57 UTC, Mayank447 commented on README.md
> +`</pre>`
Fixed

2024-08-09 07:10 UTC, Mayank447 commented on README.md
> +- run `pip install .`
Changed

2024-08-09 07:11 UTC, Mayank447 commented on README.md
> +  - `example_scripts` folder for example script usage of the DiracOperator, Spectrum classes, methods and a boiler-plate to begin with.
Changed

2024-08-09 07:12 UTC, Mayank447 commented on README.md
> +  - `tutorial.md` for a step-by-step guide on how to use the classes and methods and a bit of theory behind the implementation (history behind the project).
I am not done with tutorial.md

2024-08-09 07:15 UTC, Mayank447 commented on README.md
> +Applies the given Dirac operator to the input coefficients as per the given input and output spaces.
Fixed

2024-08-09 07:15 UTC, Mayank447 commented on README.md
> +The DiracOperator class provides several methods to work with the Dirac operator in both real and spectral domains.
Fixed

2024-08-09 07:15 UTC, Mayank447 commented on README.md
> +- spectrum: The spectrum class object that represents the spectrum of the given system / operator.
Changed

2024-08-09 07:16 UTC, Mayank447 commented on README.md
> +- coefficients (np.ndarray): An array of coefficients in the input space.
Changed

2024-08-09 07:16 UTC, Mayank447 commented on README.md
> +- np.ndarray: An array of coefficients in the output space.
Changed

2024-08-09 07:17 UTC, Mayank447 commented on README.md
> +Private function to compute the eigenvalues of the 1D derivative operator.
Changes made

2024-08-09 08:58 UTC, chillenzer commented on README.md
> +- run `pip install .`
Ah, sorry. Then, it's something like `./Pseudo-Spectral-Discretization` but it's not important.

2024-08-09 08:59 UTC, chillenzer commented on README.md
> +  - `tutorial.md` for a step-by-step guide on how to use the classes and methods and a bit of theory behind the implementation (history behind the project).
Then remove that piece of information for now and add it once it's correct.

2024-08-09 09:19 UTC, chillenzer requested changes
Here's another round. Please be particularly vigilant concerning the meaning of "everywhere". Don't just search-replace one expression but think about what this change means and how it is to apply "everywhere".

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- `pseudospectral` folder contains all the source code of the project which are mainly `.py` files broadly categorized into Dirac Operator and Spectra python files.
```suggestion
- `pseudospectral` folder contains all the source code of the project which are mainly `.py` files broadly categorized into Dirac operator and Spectra python files.
```

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +  - `example_scripts` folder for example script usage of the `DiracOperator`, `Spectrum` classes, methods and a boiler-plate to begin with.
```suggestion
- `example_scripts` folder for example script usage of the `DiracOperator`, `Spectrum` classes, methods and a boiler-plate to begin with.
```

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +    ├── spectra
```suggestion
    └── spectra
```

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +        ├── free_fermions_2D.py
```suggestion
        └── free_fermions_2D.py
```
and so on...

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- run `pip install .`
But even better: https://pip.pypa.io/en/stable/topics/vcs-support/
Something like this should work: (Figure out the details yourself if you like or leave it as is)
```bash
python -m pip install 'SomeProject@git+https://git.repo/some_pkg.git@1.3.1'
```
(from bullet 5 [here](https://pip.pypa.io/en/stable/cli/pip_install/#examples).

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +  - `example_scripts` folder for example script usage of the DiracOperator, Spectrum classes, methods and a boiler-plate to begin with.
```suggestion
  - `example_scripts` folder for example script usage of the DiracOperator, Spectrum classes, methods and a boilerplate to begin with.
```

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- coefficients (np.ndarray): An array of coefficients in the input basis.
```suggestion
- `coefficients` (`np.ndarray`): An array of coefficients in the input basis.
```
"Everywhere" meant whenever you've got a code entity.

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- input_basis (str): Specifies the space of the input coefficients. Valid values are 'real' and 'spectral'.
```suggestion
- input_basis (str): Specifies the basis of the input coefficients. Valid values are 'real' and 'spectral'.
```
everywhere.

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- L: The length of the domain.
```suggestion
- L: The physical length of the domain.
```
everywhere.

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- ValueError: If eigenvalue_index is not in the range from 0 to L - 1.
Also here!

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +The Derivative1D class provides methods to work with the 1D derivative operator in both real and spectral domains with periodic boundary conditions.
This meant: Please add some useful information here as done for the `DiracOperator` case.

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- spectrum: The spectrum class object that represents the spectrum of the given system / operator.
Not everywhere. It meant: For all code entities.

2024-08-09 09:19 UTC, chillenzer commented on README.md
> +- eigenvalue_index (int): The index of the eigenvalue. This range is from 0 to L - 1.
Not done everywhere!

2024-08-09 20:12 UTC, chillenzer commented on README.md
> +  - `tutorial.md` for a step-by-step guide on how to use the classes and methods and a bit of theory behind the implementation (history behind the project).
Okay. I'll give you this one.

2024-08-09 20:13 UTC, chillenzer approved these changes

2024-08-09 20:15 UTC, merged