Tests
Mayank447/Pseudo-Spectral-Discretization pull request #3
Opened 2024-07-16 07:07 UTC by Mayank447

Wrote basic functions for the Dirac Operator class and test functions in real space, spectral space and transform

2024-07-16 08:16 UTC, chillenzer commented
There is exactly a single test passing and the `pyproject.toml` is incomplete to the point that the project is uninstallable and it's quite hard to actually run the tests. Did you run the test before submission?

2024-07-18 14:50 UTC, chillenzer requested changes
Good work! Thank you!

I've put in my first charge of comments. Didn't look at the test yet.

2024-07-18 14:50 UTC, chillenzer commented on Eigenmodes.py
Remove this file. We've started off fresh.

2024-07-18 14:50 UTC, chillenzer commented on README.md
This is totally out of date. Remove or update.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +## Dirac Operator -
```suggestion
## Dirac Operator
```

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +## Usage -
```suggestion
## Usage
```

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +Defining a spectral representation (a class) [input - eigenfunctions, corresponding eigenvalues, space]. User gives the spectrum object to the Dirac Operator while initializing the object. [We will b
Make this a well-phrased paragraph.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +            raise ValueError("Unsupported space transformation.")
The `_eigenvalues()` method is missing.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +            return np.fft.ifft(input_vector) * np.sqrt(self.n_real)
There is likely a way to write this more concise. We should consider finding that.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +    def transform(self, input_vector, input_space, output_space):
We should consider passing `input_space` and `output_space` as [enums](https://docs.python.org/3/library/enum.html). The `Spectrum` itself could then define the enum, so that the user can get a quick overview over what this spectrum is capable of.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +Take your `spectral_representation` from the last section and define your input:
We don't define a `spectral_representation` above. Either add that to the example above or to the example below.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +input_vector = [...]
Put values here.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +assert result == eigenvalue * input_vector
Make an example folder that contains exactly this code as a script (including all setup that's needed), so the user has a nice starting point for their own application.

2024-07-18 14:50 UTC, chillenzer commented on documentation.md
> +assert expected == actual
Remove.

2024-07-18 16:23 UTC, Mayank447 commented on pseudospectral/spectrum.py
> +import scipy.fft
According to numpy documentation (https://numpy.org/devdocs/reference/routines.fft.html). The SciPy module scipy.fft is a more comprehensive superset of numpy.fft, which includes only a basic set of routines

2024-07-18 17:59 UTC, Mayank447 commented on README.md
I will update

2024-07-19 06:16 UTC, chillenzer commented on pseudospectral/spectrum.py
> +import scipy.fft
I presume we won't need that generality but okay.

2024-07-19 06:37 UTC, chillenzer requested changes
~~Also: The tests still don't pass.~~

Sorry, might have forgotten to pull the latest version.

2024-07-19 06:37 UTC, chillenzer commented on test/test_real_space.py
> +    eigenfunction = operator.spectrum.eigenfunction(arbitrary_index)(np.arange(L))
```suggestion
    eigenfunction = operator.spectrum.eigenfunction(arbitrary_index)(np.arange(n)/n*L)
```
You're missing your length parameter here. This is why I advocated for having it set to one in the first place! Please consider again to remove this feature for now. We can add it back when we need it.

Scrolling through the rest I see that change must, of course, be made everywhere.

2024-07-19 06:37 UTC, chillenzer commented on test/test_real_space.py
> +    operator = DiracOperator(Derivative1D(num_lattice_points=n, L=L))
We should use [fixtures](https://docs.pytest.org/en/latest/explanation/fixtures.html) for providing `arbitrary_index` and `spectrum` (separately). That way we have a more concise, easier-to-read test and a very straightforward way to generalise this test to other spectra/indices. Of course, this applies to every test.

2024-07-19 06:37 UTC, chillenzer commented on test/test_real_space.py
> +    # print("Result: ", result, '\n')
Remove! These and all others (I won't tag them all).

2024-07-19 06:37 UTC, chillenzer commented on test/test_real_space.py
> +#     main()
Remove! You can have those in your local branch as a reminder if you prefer but not in mainline.

2024-07-19 06:37 UTC, chillenzer commented on test/test_spectral_space.py
> +    eigenfunction[arbitrary_index] = 1
```suggestion
    eigenfunction = np.eye(n)[arbitrary_index]
```
There is another mistake concerning `n` vs. `L`. Please remove this feature as it is obviously a source of distraction from our real task.

2024-07-19 06:37 UTC, chillenzer commented on test/test_spectral_space.py
> +    eigenfunction_1[arbitrary_index[0]], eigenfunction_2[arbitrary_index[1]] = 1, 1
```suggestion
    eigenfunction_1, eigenfunction_2 = np.eye(n)[arbitrary_index]
```

2024-07-19 06:37 UTC, chillenzer commented on test/test_spectral_space.py
> +    # print("All tests passed!")
As above.

2024-07-19 06:37 UTC, chillenzer commented on test/test_transform.py
> +    array = np.arange(L)
As above.

2024-07-19 06:37 UTC, chillenzer commented on test/test_transform.py
> +    expected[arbitrary_index] = 1.0
As above.

2024-07-19 06:37 UTC, chillenzer commented on test/test_transform.py
> +from pseudospectral import DiracOperator, Derivative1D
We don't need an operator here. This is a property of the spectrum.
```suggestion
from pseudospectral import Derivative1D
```
and write all the tests using the spectrum itself.

2024-07-19 06:37 UTC, chillenzer commented on test/test_transform.py
> +    operator = DiracOperator(Derivative1D(L, n))
There a duplication. Remove!

2024-07-19 06:37 UTC, chillenzer commented on test/test_transform.py
> +
As above.

2024-07-19 07:28 UTC, Mayank447 commented on Eigenmodes.py
Done

2024-07-19 07:29 UTC, Mayank447 commented on pseudospectral/dirac_operator.py
> +class DiracOperator:
I am not sure but in future we may use some properties of Dirac Operator in the class. In that case it won't be justified to call this Linear operator since Dirac Operators are special cases of Linear Operators

2024-07-19 07:32 UTC, Mayank447 commented on test/.cph/.test_transform.py_d2d6822c808b8165c140db0a7be46aff.prob
Done

2024-07-19 07:38 UTC, Mayank447 commented on test/test_real_space.py
> +    eigenfunction = operator.spectrum.eigenfunction(arbitrary_index)(np.arange(L))
I set n=L as you suggested. So therefore it boils down to my formula

2024-07-19 07:42 UTC, chillenzer commented on pseudospectral/dirac_operator.py
> +class DiracOperator:
No, we won't. If we do so, we'll build something more specific on top of this class.

2024-07-19 07:46 UTC, chillenzer commented on test/test_real_space.py
> +    eigenfunction = operator.spectrum.eigenfunction(arbitrary_index)(np.arange(L))
Well, the important thing is not so much if it works (right now) or not but if it is semantically correct. And this isn't...

But on a more practical note, I'm aware that this test works for the default parameters. But you've made them function arguments, so someone could come along and pass something else. Then, this would be wrong.

2024-07-19 11:02 UTC, Mayank447 commented on test/test_transform.py
> +from pseudospectral import DiracOperator, Derivative1D
Done

2024-07-22 11:41 UTC, Mayank447 commented on test/test_real_space.py
> +    operator = DiracOperator(Derivative1D(num_lattice_points=n, L=L))
Implemented

2024-07-22 12:49 UTC, chillenzer commented on pseudospectral/derivative_1D.py
Create a folder `spectra` and move both implemented spectra there.

2024-07-22 12:49 UTC, chillenzer commented on pseudospectral/dirac_operator.py
> +class DiracOperator:
Offline discussion: Do it later (see #4).

2024-07-22 12:49 UTC, chillenzer commented on pseudospectral/dirac_operator.py
> +class DiracOperator:
Offline discussion: Do it later (see https://github.com/Mayank447/Pseudo-Spectral-Discretization/issues/4).

2024-07-22 13:07 UTC, chillenzer requested changes
The code is starting to get into a great shape. Thanks for your good work!

Two tiny things in the comments. Other than that we'll split up the PR and then it is ready to merge.

2024-07-24 08:58 UTC, merged