Fixed scalar-product in Derivative1D
Mayank447/Pseudo-Spectral-Discretization pull request #31
Opened 2024-08-15 14:33 UTC by Mayank447

Fixes #30

2024-08-15 16:47 UTC, chillenzer requested changes
Also, please remove [this line](https://github.com/Mayank447/Pseudo-Spectral-Discretization/blob/f73e3b5846e72a0ff28b57e4844ffee66a5a8299/test/test_spectra.py#L33) and the corresponding comment. I was wrong because I assumed that those formulae from the PR description would have to hold for the same form of the scalar product, but of course that form is different in the two bases.

2024-08-15 16:47 UTC, chillenzer commented on pseudospectral/spectra/derivative_1D.py
> +            return rhs @ lhs.transpose().conjugate()
I'd say either
```suggestion
            return rhs @ lhs.transpose().conjugate() * self.a
        elif input_basis == "spectral":
            return rhs @ lhs.transpose().conjugate()
```
or
```suggestion
            return rhs @ lhs.transpose(-1, -2).conjugate() * self.a
        elif input_basis == "spectral":
            return rhs @ lhs.transpose(-1, -2).conjugate()
```
it's up to you.

2024-08-15 20:31 UTC, Mayank447 commented
I have made the suggested changes.

2024-08-16 06:39 UTC, chillenzer approved these changes

2024-08-16 06:39 UTC, merged