Boundary conditions 1 d
Mayank447/Pseudo-Spectral-Discretization pull request #43
Opened 2024-08-21 23:03 UTC by chillenzer

Implement twisted boundary conditions for the 1D derivative operator.

2024-08-22 09:02 UTC, Mayank447 commented
I will test this code with example script on sine derivative defined over [0, pi). If it works will merge

2024-08-22 20:30 UTC, chillenzer commented
Did it myself and, in fact, found a wrong normalisation. Now everything looks good.

2024-08-28 09:37 UTC, Mayank447 commented on test/test_boundary_conditions.py
> +    assert np.allclose(np.exp(2.0j * np.pi * spectrum.theta) * eigenfunctions(*spectrum.lattice()), eigenfunctions(spectrum.lattice()[0] + spectrum.L))
```suggestion
spectral_representation = np.eye(spectrum.total_num_lattice_points)
real_space_representation = spectrum.transform(spectral_representation, "spectral", "real")
eigenfunction = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points))
```

2024-08-28 09:46 UTC, Mayank447 requested changes
Few minor changes

2024-08-28 09:46 UTC, Mayank447 commented on test/test_boundary_conditions.py
> +    eigenfunctions = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points).reshape(-1, 1))
```suggestion
    eigenfunctions = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points))
```

2024-08-28 09:46 UTC, Mayank447 commented on test/test_boundary_conditions.py
> +    eigenfunctions = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points).reshape(-1, 1))
```suggestion
    eigenfunctions = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points))
```

2024-08-28 09:46 UTC, Mayank447 commented on test/test_boundary_conditions.py
> +    spectral_representation = np.eye(spectrum.total_num_lattice_points)[1, :]
```suggestion
    spectral_representation = np.eye(spectrum.total_num_lattice_points)
```

2024-08-28 09:46 UTC, Mayank447 commented on test/test_boundary_conditions.py
> +    eigenfunction = spectrum.eigenfunction([1])
```suggestion
    eigenfunction = spectrum.eigenfunction(np.arange(spectrum.total_num_lattice_points))
```

2024-08-28 09:46 UTC, Mayank447 commented on pseudospectral/spectra/derivative1D.py
> +        return tmp
```suggestion
        return I2PI * (np.fft.fftfreq(self.total_num_lattice_points, d=self.a) + self.theta / self.L)
```

2024-08-28 09:46 UTC, Mayank447 commented on pseudospectral/spectra/derivative1D.py
> +            return scipy.fft.fft(np.exp(-I2PI * self.theta / self.L * self.lattice("real")[0]) * input_vector, norm="ortho") * np.sqrt(self.a)
```suggestion
            premultiplier = np.exp(-I2PI * self.theta / self.L * self.lattice("real")[0])
            return scipy.fft.fft(premultiplier * input_vector, norm="ortho") * np.sqrt(self.a)
```

2024-08-28 09:46 UTC, Mayank447 commented on pseudospectral/spectra/derivative1D.py
> +            return np.exp(I2PI * self.theta / self.L * self.lattice("real")[0]) * scipy.fft.ifft(input_vector, norm="ortho") / np.sqrt(self.a)
```suggestion
            postmultiplier = np.exp(I2PI * self.theta / self.L * self.lattice("real")[0])
            return postmultiplier * scipy.fft.ifft(input_vector, norm="ortho") / np.sqrt(self.a)
```

2024-08-28 12:11 UTC, merged