Derivative 1D
Mayank447/Pseudo-Spectral-Discretization pull request #5
Opened 2024-07-22 13:25 UTC by Mayank447

Split of the test branch as discussed in #3

2024-07-22 14:21 UTC, chillenzer requested changes
Looks good! Some very minor last things.

2024-07-22 14:21 UTC, chillenzer commented on README.md
> +The `DiracOperator` class implements the Dirac operator with methods for applying it to spectral coefficients, computing eigenvalues and eigenfunctions, generating a lattice structure, and transformi
```suggestion
The `DiracOperator` class implements the Dirac operator with methods for applying it to vectors in real-space and spectral representation. It takes a spectrum as defined below.

# Spectrum

Spectra are defined as classes which provide, among other things, knowledge about the eigenvalues and the transformations between real and spectral space.
```

2024-07-22 14:21 UTC, chillenzer commented on pseudospectral/dirac_operator.py
> +            raise ValueError("Unsupported space transformation.")
```suggestion
            raise ValueError(f"Unsupported space transformation from {input_space} to {output_space}.")
```

2024-07-22 14:21 UTC, chillenzer commented on pseudospectral/spectra/derivative_1D.py
> +        return 1j * 2 * np.pi * np.arange(self.num_lattice_points) / self.L
For future reference: A future PR should address #6.

2024-07-22 14:21 UTC, chillenzer commented on pseudospectral/spectra/derivative_1D.py
> +            raise ValueError("Unsupported space transformation.")
```suggestion
            raise ValueError(f"Unsupported space transformation from {input_space} to {output_space}.")
```

2024-07-22 14:40 UTC, chillenzer commented on pyproject.toml
> +    "pre-commit==4.6.0"
Not yet, either add your `.pre-commit-config.yaml` or remove this line.

2024-07-23 15:53 UTC, Mayank447 commented on pyproject.toml
> +    "pre-commit==4.6.0"
Done

2024-07-24 08:57 UTC, chillenzer approved these changes

2024-07-24 08:58 UTC, merged