Fermion 2 d
Mayank447/Pseudo-Spectral-Discretization pull request #9
Opened 2024-07-30 12:08 UTC by Mayank447

2024-07-30 13:52 UTC, chillenzer reviewed
Just a few comments already.

2024-07-30 13:52 UTC, chillenzer commented on .pre-commit-config.yaml
> +    -   id: black
I think I would prefer to add the `ruff` formatter and remove the `black` formatter.

2024-07-30 13:52 UTC, chillenzer commented on .pre-commit-config.yaml
> +    # - id: ruff-format
See above.

2024-07-30 13:52 UTC, chillenzer commented on README.md
> +</pre>
As discussed offline, unless you have a system that provably doesn't let this become outdated, I think this is a level of detail we cannot maintain consistently.

2024-07-30 13:52 UTC, chillenzer commented on README.md
> +- `pseudospectral/spectra` folder contains spectrum class implementations.
```suggestion
- `pseudospectral/spectra` folder contains spectrum class implementations. Take a look if your use case is already implemented and otherwise take it as an inspiration for how to write a spectrum yourself.
```

2024-07-30 13:52 UTC, chillenzer commented on README.md
> +```from pseudospectral import DiracOperator, FreeFermions2D```
````suggestion
```python3
from pseudospectral import DiracOperator, FreeFermions2D
```
````

2024-07-30 13:52 UTC, chillenzer commented on README.md
> +##  DiracOperator Class
This last part is probably also a level of detail, we don't want to maintain manually. If you want to have something like this, set up [Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) to [generate the API documentation automatically from the docstrings](https://www.sphinx-doc.org/en/master/tutorial/automatic-doc-generation.html).

2024-07-30 13:52 UTC, chillenzer commented on example_scripts/cosine-derivative.py
> +def cosine(x):
This is unused.

2024-07-30 13:52 UTC, chillenzer commented on example_scripts/cosine-derivative.py
Of course, there are all the things we just talked about in the meeting. I won't write them down again.

2024-07-30 13:52 UTC, chillenzer commented on example_scripts/cosine-derivative.py
> +    x = np.arange(10)
```suggestion
    x = np.arange(10)
    y = cosine(x)
    plt.plot(x, y)
```

2024-07-30 13:52 UTC, chillenzer commented on example_scripts/cosine-derivative.py
> +    plt.plot(x, np.abs(d.apply_to(x)))
```suggestion
    plt.plot(x, np.abs(d.apply_to(y)))
```

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +def cartisean_product(array_1, array_2):
```suggestion
def cartesian_product(array_1, array_2):
```

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +    return np.array([[x,y] for x in array_1 for y in array_2])
Never write such a function. There is functionality for that in numpy.

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +    The operator is discretized on p_0 2D lattice with n_t lattice points in the time axis and n_x lattice points in the x axis.
Wrong search-replace.

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +        n_x: number of lattice points in the x axis (odd)
Check these requirements on the input, please.

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
>      def __init__(self, mu, m, L_t, L_x, n_t, n_x):
```suggestion
    def __init__(self, n_t, n_x, *, mu=0, m=0, L_t=1, L_x=1):
```
Reasoning:
- `n_t` and `n_x` are always required and their order is natural.
- All other parameters should have reasonable defaults when they are not given because the user might not even be aware they exist.
- All other parameters should be named as to not confuse them (a line `1, 2, 3, 4, 5, 6` does not really tell you much about what's going on here).

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +        p_0, p_1 = index[0], index[1]
```suggestion
        p_0, p_1 = index
```

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
> +        return lambda x, t: np.exp(1j * (2 * np.pi) * (self.n_t/self.L_t * (p_0 * t) + (self.n_x - 1)/self.L_x * p_1 * x)) * np.array([p_1, np.sqrt((p_0 - self.mu)**2 + p_1**2) + sign * (p_0 - self.m
Normalisation.

2024-07-30 13:52 UTC, chillenzer commented on tests/test_real_space.py
>  def arbitrary_index_single_eigenfunction(index=1):
This is unused. Remove.

2024-07-30 13:52 UTC, chillenzer commented on tests/conftest.py
I think I would prefer to have this in a file that's explicitly imported. Otherwise, it is hard to find out where that fixture is coming from (particularly for a person that is not aware of the `conftest.py` mechanism).

2024-07-30 13:52 UTC, chillenzer commented on tests/test_real_space.py
> +    return [(x,y) for x in range(4) for y in range(4)]
Unused. Remove.

2024-07-30 13:52 UTC, chillenzer commented on pseudospectral/spectra/derivative_1D.py
Everything discussed offline.

2024-07-30 13:52 UTC, chillenzer commented on pyproject.toml
> +    "ruff==~0.5.0",
Don't think that's necessary. Should be pulled in from `pre-commit` directly.

2024-07-30 13:52 UTC, chillenzer commented on tests/test_spectral_space.py
> +def arbitrary_index_single_eigenfunction(spectrum):
as above

2024-07-30 13:52 UTC, chillenzer commented on tests/test_spectral_space.py
>  @pytest.fixture
Unused.

2024-08-02 01:16 UTC, Mayank447 commented on README.md
> +</pre>
The way to automatically generate the directory structure is to run the tree command in terminal and then just copy paste the output in the markdown.

2024-08-16 21:15 UTC, chillenzer requested changes
Good work! Great that it's finally running! I have only commented minor things and I'll commit some of them myself right after submission (can't do that from a pending review).

There are a number of things about this code that I have outsourced to issues for later clean-up: #33, #34, #35, #36. I think none of those is blocking for this PR but particularly the last one (test unification) should have high priority.

2024-08-16 21:15 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +        premultiplier_x = np.exp(-I2PI * (self.theta_x/self.L_x) * np.arange(self.n_x))
Wait. Theta is used! Does it work? If so, your docstring somewhere at the top should be corrected about the boundary conditions. If not, this can be simplified.

2024-08-16 21:15 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +
Is this supposed to stay? If so, why?

2024-08-16 21:15 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +            return self.eigenvalues
I think this is inconsistent: If the output for `'real'` is a tuple of two flattened arrays, I'd expect the spectral lattice to be the same type. In general, I'd expect `spectrum.lattice('spectral')` to return an N-dimensional entity for an N-dimensional problem. I think you'd want to return something like `self.p_t, self.p_x`.

2024-08-16 21:18 UTC, chillenzer commented on README.md
> +</pre>
Just for the record: This is already outdated! Just saying...

2024-08-16 21:20 UTC, chillenzer commented on pseudospectral/spectra/free_fermions_2D.py
>      def __init__(self, mu, m, L_t, L_x, n_t, n_x):
See #38

2024-08-16 22:00 UTC, Mayank447 commented on pseudospectral/__init__.py
> +from .spectra.fermion2D import FreeFermion2D
Changed derivative_1D to derivative1D

2024-08-16 22:04 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +        Note: p_t, p_x used in the function are scalars and not arrays.
Nope

2024-08-16 22:06 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +        sign = np.array(1 - 2*(index % 2))
Not anymore

2024-08-16 22:09 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +        eta[np.logical_and(mask, sign==-1)] = np.array([0, 1])
No, the length of eta is the len(index) not necessarily two. Also each element of eta is a vector not the identity matrix

2024-08-16 22:09 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +        ret = [0]*len(index)
Check the updated codeline

2024-08-16 22:11 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +
I was just testing out with directly applying the operator instead of diagonalising the block matrix

2024-08-16 22:11 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +
I plan to use this in a test after rewriting the function

2024-08-16 22:13 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +            return self.eigenvalues
Clearly the lengthdimensionality of self.p_t, self.p_x is n_x * n_t which is half of the real lattice. Because of the spinor structure we need to return the eigenvalues

2024-08-17 11:00 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +
Okay. Then, please, add a docstring clearly stating this intent.

2024-08-17 11:03 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +            return self.eigenvalues
No, I think that's consistent: You're returning `n_x * n_t` lattice points for `'real'`, so you should return the same number of lattice points in the spectral basis. The missing factor of two comes from the fact that this operator is acting on a space of two-component spinors. Otherwise you would have to return `2 * n_x * n_t` lattice points in `'real'` space, too.

2024-08-17 11:06 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +        eta[np.logical_and(mask, sign==-1)] = np.array([0, 1])
You're right, sorry.

2024-08-17 11:14 UTC, Mayank447 commented on pseudospectral/spectra/fermion2D.py
> +            return self.eigenvalues
Oh wait.. just realized my mistake.

2024-08-21 12:35 UTC, chillenzer requested changes
Some small things.

2024-08-21 12:35 UTC, chillenzer commented on pseudospectral/spectra/fermion2D.py
> +    sign = +-1
```suggestion
```

2024-08-21 12:43 UTC, Mayank447 commented on example_scripts/sine-derivative.py
I mean its fine removing for now, cause there is already a cosine-derivative.py and personally both of them are very similar.

2024-08-21 12:44 UTC, chillenzer commented on example_scripts/sine-derivative.py
Okay.

2024-08-21 13:30 UTC, chillenzer requested changes

2024-08-21 13:30 UTC, chillenzer commented on .DS_Store
Delete!

2024-08-21 13:38 UTC, Mayank447 commented on test/test_real_basis.py
> +#     assert np.equal(lattice, excepted).all()
Any hints on testing for only some specific spectrum param

2024-08-21 14:16 UTC, Mayank447 commented on test/test_real_basis.py
> +#     assert np.equal(lattice, excepted).all()
I did my own implementation. Have a look

2024-08-21 20:37 UTC, chillenzer approved these changes
There are still some open comments but I'll merge for the sake of moving on.

2024-08-21 20:37 UTC, merged